#!/bin/bash

# Find the logged-in user
USERNAME=$(who | grep 'tty' | awk '{print $1}' | head -n 1)
USERID=$(id -u $USERNAME)

# Export the required environment variables
export XAUTHORITY=/home/$USERNAME/.Xauthority
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USERID/bus

# Check if we are root or not, then use the right user for notifications
if [ "$(/usr/bin/id -u)" != "$USERID" ]; then
    sudo -u $USERNAME XAUTHORITY=/home/$USERNAME/.Xauthority DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USERID/bus /usr/bin/notify-send.py "$@"
     exit $?
else
    /usr/bin/notify-send.py "$@"
     exit $?
fi

