#!/usr/bin/env bash

function notify_success() {
    CHOICE=$(sudo blend-update-notify "BlendOS Update" "System updated successfully. Please reboot to finish the update." \
        --app-name "blendOS Update" \
        --icon blendos-logo \
        --expire-time 0 \
        --hint boolean:action-icons:true \
        --action reboot:Reboot later:Later)

         if [[ "$CHOICE" == reboot* ]]; then
        echo "Rebooting system..."
        sudo systemctl reboot
        fi

}

function notify_failure() {
    sudo blend-update-notify "BlendOS Update Failed!" "Please run 'akshara update' manually." --app-name "blendOS Update" --expire-time 0 --icon dialog-error
}

# Run the update
if akshara update; then
    notify_success
else
    notify_failure
fi